### ISSUE TITLE
Main view not consistent after star changes

### ISSUE THREAD

**Issue by maweki** [kirienko/gourmet#143]
So I've added new recipes (empty) and sorted by star. When changing the star rating, the item swaps to is correct position but receives a different id and name. When double-clicking I get the wrong recipe (the one that fits the title, cranberry cookies in that case) and not the empty one. I guess there's a `+-1` error somewhere.

![output](https://user-images.githubusercontent.com/613272/87326230-bf7e8d00-c532-11ea-97e6-649354bc79ab.gif)

**Comment by cydanil** [comment]
I decided to disallow users to set rating in the main window.  

On one hand, the sorting results in a buggy behaviour where the clicked recipe opens another, due to the index to recipe model not being updated.   
On another, the main treeview only allows to select recipes. Rating recipes here is not quite consistent with other UX rules.
