### ISSUE TITLE
Application preferences not available until New Recipe input screen or Recipe Card Opened

### ISSUE THREAD

**Issue by Oldbwl** [kirienko/gourmet#193]
**Actions**
1. Run Gourmet
2. select any drop down menu item

**Results**
1. No "Preferences" available
2. Opening Recipe Card or New Recipe input card has Preferences in drop down menu

**Expected Results**
1. Preferences set global items and should be accessible from Manu Recipe Index screen

**Comment by cydanil** [comment]
Thanks,
I broke this in commit [3aeda604](https://github.com/kirienko/gourmet/commit/3aeda604).
This is also responsible for the lost `plugins` preference window.

**Comment by cydanil** [comment]
Thank you for reporting this issue, I didn't notice the disappearance of this menu. It's now resolved :) 

A few more issues need to be addressed prior to releasing another alpha release, though.
The fix is available in master, and in the wheel found within this [gourmet.zip archive](https://github.com/kirienko/gourmet/files/5285774/gourmet.zip)
