### ISSUE TITLE
Fix test_allrecipes_com_plugin.py

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#20]
Import from `allrecipes.com` doesn't work properly. Though it works _somehow_. This is a low priority task.

```bash
$ nosetests gourmet/tests/test_allrecipes_com_plugin.py
/home/kir/github/gourmet/gourmet/Undo.py:2: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
E.
======================================================================
ERROR: test_parse (gourmet.tests.test_allrecipes_com_plugin.TestAllRecipesPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kir/github/gourmet/gourmet/tests/test_allrecipes_com_plugin.py", line 48, in test_parse
    instructions = [r for r in result if r[1] == "instructions"][0][0].text
IndexError: list index out of range
```

**Comment by FriedrichFroebel** [comment]
Having a quick look at the old and the new website layout for `allrecipes.com`, it seems like there have been some major changes - so just fixing the existing test case does not seem to be very helpful when it does not work with current data either.

I have been able to fix this problem for the current website using the JSON-LD script element (and an additional `bs4`-based retrieval for the servings) by modifying the `schema_org_parser` and the test file itself, but my current approach probably has lots of side effects on other parsers and the connected data handlers (`preparsed_elements` is a dictionary in my current version instead of the old list of tuples), so it would probably need more modifications (or a complete rewrite of the corresponding logic).

**Comment by maweki** [comment]
> (`preparsed_elements` is a dictionary in my current version instead of the old list of tuples)

you can use `dict.items()` to get a compatible tuple iterator. Or use the `dict([(a,b),(c,d)])` constructor to get this the other way around. So this should just be a small change at the interfaces.

**Comment by kirienko** [comment]
Well, funnily, right now the plugin doesn't even try to go to the `url`. It uses an ancient page saved in `gourmet/tests/recipe_files/allrecipes_com.html`. In this sense the test is self-contained.

But I think we should change this approach and test against the real site. But in this case we would have to probably rewrite a lot.  Maybe completely.

**Comment by kirienko** [comment]
BTW, guys, I created a [project board](https://github.com/kirienko/gourmet/projects/1) for fixing tests. I encourage everyone to move cards there :smiley: 

Just to distribute the work more effectively.

**Comment by FriedrichFroebel** [comment]
With #53 this has been fixed.
