### ISSUE TITLE
Fix test_exporters.py

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#22]
This one might be not an easy task.

This is a very old test (2006) which relies on some `reference_setup`.
It tries to import an argument that presumably no longer exist.
The architecture of this test is also unclear. Maybe it's easier to rewrite the whole test from scratch.

Priority is unclear (from medium to low).

**Comment by takluyver** [comment]
I started trying to fix it, but it's all based around testing the entries in `exporters.exporter_dict`, which doesn't exist. It looks like this could have been superseded by the plugin based system which `test_exportManager` tests. So I think this file can simply be deleted. Does that make sense? Or does someone have more insight about why it might still be useful?

**Comment by kirienko** [comment]
I tried to go into it some time ago, and I also had a suspicion that that's just a piece of dead code. But I hadn't found enough evidence of that. Maybe git still stores the answer somewhere in its deeps.

**Comment by takluyver** [comment]
I did a bit of archaeology. `exporters.exporter_dict`, which this file uses, was removed in commit cedf47c0c070fae9ccc50ddd7044d9f401ac608c in 2008. The commit message says that

> Making the change to a plugin system, this means adding logs of plugins and moving around import/export modules. As of this commit, exporters have been fully plugin-a-fied

Which supports my theory that this was testing the thing which was replaced by exportManager, which finds and uses plugins.

The test file has hardly been touched since then - it looks like the only commits to touch it have been reorganisations and cleanups touching many files. So I'm pretty sure it's a relic, and I've removed it in PR #114.
