### ISSUE TITLE
Fix test_importers.py

### ISSUE THREAD

**Issue by kirienko** [kirienko/gourmet#28]
Looks very similar to #27, but might become more difficult.

3 tests out of 3 are failing:
```
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by kirienko** [comment]
Well, the problem is way much deeper than just inheritance from `BaseException`. Because after one fixes that, he come to the next question:

**Should we support any encoding apart from UTF8?**

What we have here:
```python
class CheckEncoding:

    """A class to read a file and guess the correct text encoding."""

    encodings = ['iso8859','ascii','latin_1','cp850','cp1252','utf-8']
    all_encodings= ['ascii','cp037','cp424',
                        'cp437','cp500','cp737','cp775','cp850','cp852',
                        'cp855','cp856','cp857','cp860','cp861','cp862',
                        'cp863','cp864','cp865','cp869','cp874','cp875',
                        'cp1006','cp1026','cp1140','cp1250','cp1251',
                        'cp1252','cp1253','cp1254','cp1255','cp1256',
                        'cp1258','latin_1','iso8859_2','iso8859_3',
                        'iso8859_4','iso8859_5','iso8859_6','iso8859_7',
                        'iso8859_8','iso8859_9','iso8859_10','iso8859_13',
                        'iso8859_14','iso8859_15','koi8_r','koi8_u',
                        'mac_cyrillic','mac_greek','mac_iceland','mac_latin2',
                        'mac_roman','mac_turkish','utf_16','utf_16_be',
                        'utf_16_le','utf_7','utf_8']
```

IMO the answer is NO.

Any opinions on that?

**Comment by maweki** [comment]
> IMO the answer is NO.

I agree. Maybe we do something dynamic on importing (but then we read the encoding from http headers, etc.). Internally, we would only use unicode python-strings.

**Comment by takluyver** [comment]
From what I saw, it's probably necessary to support whatever encodings files might be in in order to do a good job of importing them.

However, I'm not sure `CheckEncoding` is actually doing this in a useful way. `.test_encoding()` is meant to iterate through a list of encodings to find the first one which can decode some bytes. But the first one it tries, `'iso8859'`, is an alias for `iso8859-1`, which can decode any bytes, so it will always return that, unless I've missed something. A better approach would be to guess with something like [chardet](https://pypi.org/project/chardet/).

The rest of the file seems to offer a dialog for the user to pick the encoding if more than one could work for a file. This is more reasonable. But there will *always* be more than one possible encoding: several of the ISO-8859 encodings can decode any bytes. So it might make sense to e.g. only show it when the confidence score from chardet is below some threshold.

**Comment by maweki** [comment]
> From what I saw, it's probably necessary to support whatever encodings files might be in in order to do a good job of importing them.

Do users in 2020 actually have plain-text non-unicode files (most other formats/webpages/etc. do convey their encoding to the requester in some way) that we actually want to import?

**Comment by takluyver** [comment]
I don't know much about this space, but I could imagine people still have files from other recipe manager programs saved in a locale-specific encoding. Maybe it's rare enough now that we don't need to worry about it, but it's not particularly hard to support imports from a wide range of encodings if we want to. As you say, once data is imported it should all be handled as unicode.
